// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using to_do_list_api.Persistance;

#nullable disable

namespace to_do_list_api.Migrations
{
    [DbContext(typeof(ToDoListDbContext))]
    [Migration("20231113192013_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("to_do_list_api.Entities.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15e475fd-e760-4b54-9323-cc2844725e14"),
                            Deadline = new DateTime(2023, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Studying an irregular verbs",
                            Name = "English",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = new Guid("c0a0e75a-0ea4-48a6-b69f-f1165feb52f7"),
                            Deadline = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Implement a backend in my app",
                            Name = "Coding",
                            Priority = (byte)2
                        },
                        new
                        {
                            Id = new Guid("4abf0282-c3f3-471a-8833-ac78555a47ce"),
                            Deadline = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Netflix, Games, Walking",
                            Name = "Spend some time with my girlfriend",
                            Priority = (byte)1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
